# Generated by Django 2.2.1 on 2019-07-31 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deviceusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('intime', models.TimeField()),
                ('outtime', models.TimeField()),
                ('total_time', models.CharField(max_length=255)),
                ('approval_status', models.CharField(max_length=255)),
                ('is_late', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deviceusers.Device_user')),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('approval_status', models.CharField(choices=[('Auto', 'Auto'), ('Manual', 'Manual')], default='Auto', max_length=20)),
                ('late_status', models.CharField(choices=[('On Time', 'On Time'), ('Late', 'Late')], default='On Time', max_length=20)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deviceusers.Device_user')),
            ],
            options={
                'ordering': ('-datetime',),
                'unique_together': {('user_id', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deviceusers.Device_user')),
            ],
            options={
                'ordering': ('-datetime',),
                'unique_together': {('user_id', 'datetime')},
            },
        ),
    ]
